### ISSUE TITLE
Cannot assign to value: 'axisRatios' is a 'let' constant

### ISSUE THREAD

**Issue by BhaveshJogani** [eternityz/RWBarChartView#4]
func barChartView(_ barChartView: RWBarChartView!, shouldShowAxisAtRatios axisRatios: AutoreleasingUnsafeMutablePointer<NSArray?>!, withLabels axisLabels: AutoreleasingUnsafeMutablePointer<NSArray?>!) -> Bool {
        var ar = axisRatios
        ar = [NSNumber.init(value: 0.25),NSNumber.init(value: 0.5),NSNumber.init(value: 0.75),NSNumber.init(value: 1.0)]
        return true
    }

**Comment by eternityz** [comment]
Use `axisRatios.pointee` to set pointer value.

```swift
    func barChartView(_ barChartView: RWBarChartView!, shouldShowAxisAtRatios axisRatios: AutoreleasingUnsafeMutablePointer<NSArray?>!, withLabels axisLabels: AutoreleasingUnsafeMutablePointer<NSArray?>!) -> Bool {
        let axis = [NSNumber(floatLiteral: 0.25), NSNumber(floatLiteral: 0.5), NSNumber(floatLiteral: 0.75), NSNumber(floatLiteral: 1.0)]
        axisRatios.pointee = axis as NSArray
        return true
    }
```

**Comment by BhaveshJogani** [comment]
Thanks for your support.

Its working properly now...

thanks......
